### ISSUE TITLE
Actividad 5 Realidad aumentada en sitio Web

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-irving-1#1]
[Actividad 5 Objeto en la web.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-irving-1/files/14922707/Actividad.5.Objeto.en.la.web.pdf)

**Comment by magaly1311** [comment]
Calificación 20%

**Comment by magaly1311** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
